### ISSUE TITLE
Example for reading an RTSP stream and republishing all tracks to a server

### ISSUE THREAD

**Issue by kaiiorg** [aler9/gortsplib#91]
This may be a weird usecase, but I'm trying to use gortsplib to read an RTSP stream from a camera, then publish it to an endpoint configured on rtsp-simple-server. I've attempted to do so myself, but my naive attempt isn't working correctly. See [kaiiorg/client-read-publish](https://github.com/kaiiorg/client-read-publish). For the record, I'm new to Go, so I may have committed some cardinal sin without realizing; sorry for that.

## Additional information:
1. I'm using rtsp-simple-server 0.17.13.
2. rtsp-simple-server's config is the default provided with the linux binary, but the `paths` key was modified:
```yml
paths:
  PublishedStream:
    source: publisher
  ExampleStream:
    # Just using rtsp-simple-server for consistency, a realistic usage would be connecting directly to a camera.
    source: rtsp://admin:PASSWORD@192.168.62.197/media/video1
```
3. ffplay works when I stream the ExampleStream:
    - `ffplay.exe -x 500 -rtsp_transport tcp "rtsp://192.168.62.145:8554/ExampleStream"`
    - ![image](https://user-images.githubusercontent.com/14365919/148615222-be6bfa7d-797e-4ce1-8395-b9d7bfeafb0f.png)
4. ffplay does not work when I attempt to stream my republished stream:
    - `ffplay.exe -x 500 -rtsp_transport tcp "rtsp://192.168.62.145:8554/PublishedStream"`
    - ![image](https://user-images.githubusercontent.com/14365919/148614820-b8af7d9e-358f-4258-a2c2-443cc327ed20.png)
 5. Setting both rtsp-simple-server and my test program to use TCP as the transport makes no change

## Full Usecase
One of the requirements of the program I'm writing is to:
1. Get request via HTTP or MQTT
2. Read the stream from the IP camera
    - This may require adding a header to the RTSP request(s) to stream stored files on the camera instead of the live stream. Its weird, I know.
3. Publish the stream to an instance of rtsp-simple-server. The publish url would be in the HTTP/MQTT message.
This issue would handle parts of 2 and 3.
